import {AddonPayPaywallOptions, PluginName} from "./types";

export const getAddonPayPaywallOptions = (): AddonPayPaywallOptions => {
    try {
        // @ts-expect-error: __ADDON_PAY_PAYWALL_OPTIONS__ is a virtual variable generated by ./index.ts`
        return __ADDON_PAY_PAYWALL_OPTIONS__;
    } catch (e) {
        console.error(
            `Failed to load "${PluginName}" parameters. Make sure the plugin is properly configured in the adnbn configuration file.`
        );

        throw e;
    }
};